-- Sample data for events table
INSERT INTO events (name, description, venue, date) VALUES
('Tech Conference', 'A conference about the latest in technology.', 'Convention Center', '2024-07-01'),
('Music Festival', 'An outdoor music festival.', 'City Park', '2024-07-02'),
('Art Exhibition', 'An exhibition showcasing local artists.', 'Art Gallery', '2024-07-03'),
('Food Expo', 'A showcase of international cuisines.', 'Expo Hall', '2024-07-04'),
('Literature Summit', 'A gathering of authors and book enthusiasts.', 'Library Hall', '2024-07-05');

-- Sample data for attendees table
INSERT INTO attendees (firstname, lastname, contact, event_id) VALUES
('John', 'Doe', 'john.doe@example.com', 1),
('Jane', 'Smith', 'jane.smith@example.com', 1),
('Alice', 'Johnson', 'alice.johnson@example.com', 1),
('Bob', 'Brown', 'bob.brown@example.com', 1),
('Charlie', 'Davis', 'charlie.davis@example.com', 1),
('David', 'Wilson', 'david.wilson@example.com', 2),
('Eva', 'Miller', 'eva.miller@example.com', 2),
('Frank', 'Garcia', 'frank.garcia@example.com', 2),
('Grace', 'Martinez', 'grace.martinez@example.com', 2),
('Hank', 'Rodriguez', 'hank.rodriguez@example.com', 2),
('Ivy', 'Martinez', 'ivy.martinez@example.com', 3),
('Jack', 'Lee', 'jack.lee@example.com', 3),
('Kathy', 'Harris', 'kathy.harris@example.com', 3),
('Leo', 'Clark', 'leo.clark@example.com', 3),
('Mia', 'Lewis', 'mia.lewis@example.com', 3),
('Noah', 'Walker', 'noah.walker@example.com', 4),
('Olivia', 'Hall', 'olivia.hall@example.com', 4),
('Paul', 'Allen', 'paul.allen@example.com', 4),
('Quinn', 'Young', 'quinn.young@example.com', 4),
('Ruby', 'King', 'ruby.king@example.com', 4),
('Sam', 'Wright', 'sam.wright@example.com', 5),
('Tina', 'Scott', 'tina.scott@example.com', 5),
('Uma', 'Green', 'uma.green@example.com', 5),
('Vince', 'Adams', 'vince.adams@example.com', 5),
('Wendy', 'Baker', 'wendy.baker@example.com', 5),
('Xander', 'Perez', 'xander.perez@example.com', 1),
('Yara', 'Nelson', 'yara.nelson@example.com', 1),
('Zane', 'Carter', 'zane.carter@example.com', 1),
('Adam', 'Mitchell', 'adam.mitchell@example.com', 1),
('Bella', 'Roberts', 'bella.roberts@example.com', 1),
('Chris', 'Moore', 'chris.moore@example.com', 2),
('Dana', 'Cook', 'dana.cook@example.com', 2),
('Eli', 'Murphy', 'eli.murphy@example.com', 2),
('Fiona', 'Rogers', 'fiona.rogers@example.com', 2),
('George', 'Reed', 'george.reed@example.com', 2),
('Holly', 'Bailey', 'holly.bailey@example.com', 3),
('Ian', 'Cooper', 'ian.cooper@example.com', 3),
('Jill', 'Richardson', 'jill.richardson@example.com', 3),
('Kyle', 'Howard', 'kyle.howard@example.com', 3),
('Luna', 'Ward', 'luna.ward@example.com', 3),
('Mason', 'Torres', 'mason.torres@example.com', 4),
('Nina', 'Peterson', 'nina.peterson@example.com', 4),
('Owen', 'Gray', 'owen.gray@example.com', 4),
('Piper', 'Ramirez', 'piper.ramirez@example.com', 4),
('Quincy', 'James', 'quincy.james@example.com', 4),
('Rita', 'Watson', 'rita.watson@example.com', 5),
('Sean', 'Brooks', 'sean.brooks@example.com', 5),
('Tara', 'Sanders', 'tara.sanders@example.com', 5),
('Ulysses', 'Price', 'ulysses.price@example.com', 5),
('Violet', 'Bell', 'violet.bell@example.com', 5);
